In [1]:
import matplotlib
import matplotlib.pyplot as plt
import os
import pandas as pd
import glob
import numpy as np

In [2]:
path = '/uscms/home/jieun201/nobackup/YOURWORKINGAREA/june23_ds8_labelsOnly' #these are only the positive labels
csv_files = glob.glob(path + "/*.csv")
df_labels = (pd.read_csv(file) for file in csv_files)
big_df_labels   = pd.concat(df_labels, ignore_index=True)

In [3]:
#countNumberLowPTPositiveTracks = big_df_labels[big_df_labels['pt'] < 0.2]
#countNumberLowPTPositiveTracks

In [4]:
#plt.hist(big_df_labels ['pt'],bins=np.linspace(0,3,300),histtype='stepfilled');
#plt.hist(big_df_labels ['pt'],bins=np.linspace(0,1,100),histtype='stepfilled');
#plt.xlabel(r'$p_T$ [GeV] (100 bins)')
#plt.ylabel('Tracks')
#plt.title('physical distribution of all positive pT clusters (zoomed in to show 0 to 1 GeV)')

In [5]:
physicalDistributionPT = pd.Series(big_df_labels['pt'])
physicalDistributionPT_binCounts = physicalDistributionPT.value_counts(bins=[0.11,0.14,0.18,0.22,0.28,0.36,0.44,0.56,0.70,0.88,1.11,1.40,1.76,2.19,2.80,3.52,10]).sort_index()
physicalDistributionPT_binCounts_asArray = np.array(physicalDistributionPT_binCounts)
physicalDistributionPT_binCounts_asArray 

array([ 13121, 100733, 219511, 378631, 493818, 438212, 547937, 478947,
       425033, 343590, 248865, 164286,  96929,  60015,  27423,  16405])

In [6]:
#new Ratio based on efficiency
array1 = np.array([0.02,0.07,0.20,0.36,0.46,0.59,0.70,0.79,0.84,0.87,0.89,0.90,0.90,0.91,0.91,0.92])  #binning of CMS Run 3 plot
transformPhysicalDistributionMatchCMS_Run3_Ratio = 1/array1
transformPhysicalDistributionMatchCMS_Run3_Ratio
np.round(transformPhysicalDistributionMatchCMS_Run3_Ratio,2)
#len(transformPhysicalDistributionMatchCMS_Run3_Ratio)

array([50.  , 14.29,  5.  ,  2.78,  2.17,  1.69,  1.43,  1.27,  1.19,
        1.15,  1.12,  1.11,  1.11,  1.1 ,  1.1 ,  1.09])

In [7]:
transformPhysicalDistributionMatchCMS_Run3 = physicalDistributionPT_binCounts_asArray = np.multiply(physicalDistributionPT_binCounts_asArray, transformPhysicalDistributionMatchCMS_Run3_Ratio )
transformPhysicalDistributionMatchCMS_Run3
np.round(transformPhysicalDistributionMatchCMS_Run3,3)
#len(transformPhysicalDistributionMatchCMS_Run3)

array([ 656050.   , 1439042.857, 1097555.   , 1051752.778, 1073517.391,
        742732.203,  782767.143,  606262.025,  505991.667,  394931.034,
        279623.596,  182540.   ,  107698.889,   65950.549,   30135.165,
         17831.522])

In [8]:
np.round(transformPhysicalDistributionMatchCMS_Run3,1)

array([ 656050. , 1439042.9, 1097555. , 1051752.8, 1073517.4,  742732.2,
        782767.1,  606262. ,  505991.7,  394931. ,  279623.6,  182540. ,
        107698.9,   65950.5,   30135.2,   17831.5])

In [9]:
sumTransformPhysicalDistibutionmatchCMS_Run3 = np.sum(transformPhysicalDistributionMatchCMS_Run3)
sumTransformPhysicalDistibutionmatchCMS_Run3

9034381.819357188

In [10]:
df1 = pd.read_csv('/uscms/home/jieun201/nobackup/YOURWORKINGAREA/dec6_ds8/TestSetTruePT.csv')
df2 = pd.read_csv('/home/jieun201/redo_dec6_dec8_FP/predictionsFiles.csv')
df3 = pd.read_csv('/home/jieun201/redo_dec6_dec8_FP/true.csv')
df2.columns.values[0] = "predict"
df3.columns.values[0] = "true"
df2['predict'] = df2['predict'].astype(int)
concatenate = pd.concat([df1,df2, df3], axis=1)
concatenatePos = concatenate[concatenate['pt']>0]

In [11]:
s2 = pd.Series(df1['pt'])
BigSampleValueCounts2 = s2.value_counts(bins=[0.11,0.14,0.18,0.22,0.28,0.36,0.44,0.56,0.70,0.88,1.11,1.40,1.76,2.19,2.80,3.52,10]).sort_index()
testSetTotalCounts = np.array(BigSampleValueCounts2)
testSetTotalCounts


array([ 2477, 18742, 20584,  4038,  5334,  4658,  5753,  4997,  4531,
        3662,  2667,  1742,  1048,   594,   285,   161])

In [12]:
np.sum(testSetTotalCounts)

81273

In [13]:
concatPosPredictRight1 = concatenatePos[(concatenatePos['predict'] ==1) | (concatenatePos['predict'] ==2)]
s3 = pd.Series(concatPosPredictRight1['pt'])
BigSampleValueCounts3 = s3.value_counts(bins=[0.11,0.14,0.18,0.22,0.28,0.36,0.44,0.56,0.70,0.88,1.11,1.40,1.76,2.19,2.80,3.52,10]).sort_index()
testSetPredictedAsLowPT = np.array(BigSampleValueCounts3)
testSetPredictedAsLowPT

array([ 2312, 15472, 14985,  2189,  2046,  1259,  1187,   716,   515,
         392,   248,   139,    92,    37,    26,    10])

In [14]:
makeRatio = transformPhysicalDistributionMatchCMS_Run3/testSetTotalCounts
makeRatio

array([264.85668147,  76.78171258,  53.32078313, 260.46378845,
       201.25935345, 159.45302778, 136.06242706, 121.32520018,
       111.67328772, 107.84572214, 104.8457426 , 104.78760046,
       102.76611535, 111.02786103, 105.73742047, 110.75479341])

In [15]:
np.round(makeRatio,1)

array([264.9,  76.8,  53.3, 260.5, 201.3, 159.5, 136.1, 121.3, 111.7,
       107.8, 104.8, 104.8, 102.8, 111. , 105.7, 110.8])

In [16]:
Sum = np.dot(testSetPredictedAsLowPT,makeRatio)
Sum

4188159.1373367617

In [17]:
Eff = Sum/sumTransformPhysicalDistibutionmatchCMS_Run3
Eff

0.4635800457717157